# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 72c54a78f5d106836a88798d53685d342819b619461a325274f21cc076f0c6525ca908bc4700fa728eda289a06df7c68cdcb733fd2e9a5a12f910e6290a26b69

test:
  secret_key_base: de43471fa82dc0ee600b5f3a886b653dcd4fbab0af0c8db9866d50fcebb20f5c2cf9509259d1d9131cbfba3edbc673c1d43cdb91a75d79c2c26e3318bcae228c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
